name: interprises
favicon: null
layout_spectrum: 0.5208762970287353
typography_spectrum: 0.6137781320139766
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4079440049827099
  lightness: 0.39422974502667785
  saturation: 0.008356402395293117
  rhythmicContrast: 0.596894346177578
purpose: []
