typography_spectrum: 0.76915
color:
  brandColors:
    - '#0f1427'
    - '#6d87ba'
    - '#f8ecff'
    - '#98bae7'
    - '#0045be'
  brandStrength: 0.375
  lightness: 0.39422974502667785
  saturation: 0
  rhythmicContrast: 0.596894346177578
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.93823
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2c325578-d1a2-43d0-a3f9-818bd203b1e0.jpg
name: interprises
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Hughes Interprises, Inc.'
purpose: []
