name: interprises
favicon: null
layout_spectrum: 0.5208762970287353
typography_spectrum: 0.6137781320139766
title: 'Hughes Interprises, Inc.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f1427'
    - '#6d87ba'
    - '#f8ecff'
    - '#98bae7'
    - '#0045be'
  brandStrength: 0.375
  lightness: 0.39422974502667785
  saturation: 0
  rhythmicContrast: 0.596894346177578
purpose: []
